apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    app: nginx-app
    type: backend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: nginx-secret