version: "3.8"

services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    command: yarn run start:dev user
    depends_on:
      postgres_user:
        condition: service_healthy
    ports:
      - "3001:3001"
    env_file:
      - ./apps/user/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6001:5432"
    volumes:
      - ./postgres/user:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 10s