version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: yarn run start:dev api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api-gateway/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  chat:
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
    command: yarn run start:dev chat
    ports:
      - "3003:3003"
    env_file:
      - ./apps/chat/.env
    depends_on:
      postgres_chat:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    command: yarn run start:dev user
    depends_on:
      postgres_user:
        condition: service_healthy
    ports:
      - "3001:3001"
    env_file:
      - ./apps/user/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres_user:
    image: postgres:16
    env_file:
      - ./apps/user/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6001:5432"
    volumes:
      - ./postgres/user:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 10s
  postgres_chat:
    image: postgres:16
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - ./apps/chat/.env
    ports:
      - "6002:5432"
    volumes:
      - ./postgres/chat:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 10s

