apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-app
    type: backend

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
        type: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-app
      type: backend