apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-user-secret
data:
  DATABASE_URL: {{.Values.user.DATABASE_URL | b64enc }}

  KAKAO_CLIENT_ID: {{.Values.user.KAKAO_CLIENT_ID | b64enc }}
  KAKAO_CLIENT_SECRET: {{.Values.user.KAKAO_CLIENT_SECRET | b64enc }}
  KAKAO_REDIRECT_URI: {{.Values.user.KAKAO_REDIRECT_URI | b64enc }}

  POSTGRES_USER: {{.Values.user.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{.Values.user.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{.Values.user.POSTGRES_DB | b64enc }}

  AUTH_ROUNDS: {{.Values.encryption.AUTH_ROUNDS | b64enc }}
  JWT_ACCESS_TOKEN_SECRET: {{.Values.encryption.JWT_ACCESS_TOKEN_SECRET | b64enc }}
  JWT_REFRESH_TOKEN_SECRET: {{.Values.encryption.JWT_REFRESH_TOKEN_SECRET | b64enc }}