apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name }}-gateway-config-map
data:
  HTTP_PORT: "3000"
  USER_SERVICE_HOST: "user"
  USER_SERVICE_TCP_PORT: "3001"
  CHAT_SERVICE_HOST: "chat"
  CHAT_SERVICE_TCP_PORT: "3002"
