apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-gateway-deployment
  labels:
    app: gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: kpasd002/msa-nestjs-gateway:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{.Chart.Name }}-gateway-config-map
          livenessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
            initialDelaySeconds: 5
