apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-gateway-secret
data:
  AUTH_ROUNDS: {{.Values.encryption.AUTH_ROUNDS | b64enc }}
  JWT_ACCESS_TOKEN_SECRET: {{.Values.encryption.JWT_ACCESS_TOKEN_SECRET | b64enc }}
  JWT_REFRESH_TOKEN_SECRET: {{.Values.encryption.JWT_REFRESH_TOKEN_SECRET | b64enc }}