apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pv-deployment
  labels:
    app: nginx-app
    type: backend

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
        type: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: nginx-storage
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
  selector:
    matchLabels:
      app: nginx-app
      type: backend
