// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.1
//   protoc               v5.29.1
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = "user";

/** enum */
export enum TokenType {
  ACCESS = 0,
  REFRESH = 1,
  UNRECOGNIZED = -1,
}

export enum UserRoleEnum {
  USER = 0,
  SUPER = 1,
  UNRECOGNIZED = -1,
}

/** func definition */
export interface HashPasswordRequest {
  password: string;
  salt?: string | undefined;
}

export interface HashPasswordResponse {
  hash: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
}

export interface ParseBearerTokenRequest {
  token: string;
  type?: TokenType | undefined;
}

export interface ParseBearerTokenResponse {
  sub: number;
  email: string;
  role: UserRoleEnum;
  type: TokenType;
  exp: number;
}

export interface GetUserRequest {
  id: number;
}

export interface GetUserResponse {
  id: number;
  email: string;
  username: string;
}

export interface SingUpRequest {
  email: string;
  password: string;
  name: string;
}

export interface SingUpResponse {
  id: number;
}

export const USER_PACKAGE_NAME = "user";

export interface AuthServiceClient {
  login(request: LoginRequest): Observable<LoginResponse>;

  parseBearerToken(request: ParseBearerTokenRequest): Observable<ParseBearerTokenResponse>;

  /** rpc verifyToken(VerifyTokenRequest) returns (VerifyTokenResponse); */

  hashPassword(request: HashPasswordRequest): Observable<HashPasswordResponse>;
}

export interface AuthServiceController {
  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  parseBearerToken(
    request: ParseBearerTokenRequest,
  ): Promise<ParseBearerTokenResponse> | Observable<ParseBearerTokenResponse> | ParseBearerTokenResponse;

  /** rpc verifyToken(VerifyTokenRequest) returns (VerifyTokenResponse); */

  hashPassword(
    request: HashPasswordRequest,
  ): Promise<HashPasswordResponse> | Observable<HashPasswordResponse> | HashPasswordResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "parseBearerToken", "hashPassword"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";

export interface UserServiceClient {
  signUp(request: SingUpRequest): Observable<SingUpResponse>;

  getUser(request: GetUserRequest): Observable<GetUserResponse>;
}

export interface UserServiceController {
  signUp(request: SingUpRequest): Promise<SingUpResponse> | Observable<SingUpResponse> | SingUpResponse;

  getUser(request: GetUserRequest): Promise<GetUserResponse> | Observable<GetUserResponse> | GetUserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["signUp", "getUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
