apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: {{.Chart.Name }}-chat-cluster-ip
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: chat
  type: ClusterIP
