apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: {{.Chart.Name }}-chat-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: chat
  type: ClusterIP
