apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-chat-deployment
  labels:
    app: chat
spec:
  replicas: {{ .Values.chat.replicas }}
  selector:
    matchLabels:
      app: chat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat-container
          image: kpasd002/msa-nestjs-chat:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{.Chart.Name }}-chat-config-map
          livenessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
