apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-chat-secret
data:
  DATABASE_URL: {{.Values.chat.DATABASE_URL | b64enc}}
  MONGOOSE_USER: {{.Values.chat.MONGOOSE_USER | b64enc}}
  MONGOOSE_PASSWORD: {{.Values.chat.MONGOOSE_PASSWORD | b64enc}}
  MONGOOSE_DB: {{.Values.chat.MONGOOSE_DB | b64enc}}

