export const ENVIRONMENT_KEYS = {
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  AUTH_ROUNDS: 'AUTH_ROUNDS',
  HTTP_PORT: 'HTTP_PORT',
  NODE_ENV: 'NODE_ENV',
  DATABASE_URL: 'DATABASE_URL',
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_CLIENT_SECRET: 'KAKAO_CLIENT_SECRET',
  KAKAO_REDIRECT_URI: 'KAKAO_REDIRECT_URI',
};
