export const ENVIRONMENT_KEYS = {
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  AUTH_ROUNDS: 'AUTH_ROUNDS',
  HTTP_PORT: 'HTTP_PORT',
  TCP_PORT: 'TCP_PORT',
  NODE_ENV: 'NODE_ENV',
  DATABASE_URL: 'DATABASE_URL',
  HOST: 'HOST',

  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_CLIENT_SECRET: 'KAKAO_CLIENT_SECRET',
  KAKAO_REDIRECT_URI: 'KAKAO_REDIRECT_URI',

  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',

  /* Microservices */
  USER_SERVICE_HOST: 'USER_SERVICE_HOST',
  USER_SERVICE_TCP_PORT: 'USER_SERVICE_TCP_PORT',
  CHAT_SERVICE_HOST: 'CHAT_SERVICE_HOST',
  CHAT_SERVICE_TCP_PORT: 'CHAT_SERVICE_TCP_PORT',

  GRPC_USER_SERVICE_URL: 'GRPC_USER_SERVICE_URL',
  GRPC_CHAT_SERVICE_URL: 'GRPC_CAHT_SERVICE_URL',
};
