name: Build and Deploy

on:
  push:
    branches:
      - base
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{sercets.DOCKER_USERNAME}}
          password: ${{sercets.DOCKER_PASSWORD}}
      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t kpasd002/msa-nestjs-gateway -t kpasd002/msa-nestjs-gateway:${{github.sha}} -f ./apps/api-gateway/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t kpasd002/msa-nestjs-user -t kpasd002/msa-nestjs-user:${{github.sha}} -f ./apps/user/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t kpasd002/msa-nestjs-chat -t kpasd002/msa-nestjs-chat:${{github.sha}} -f ./apps/chat/Dockerfile --target production --push .

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist