apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-app
    type: backend
  type: NodePort
  ports:
    - port: 80 # 서비스 포트
      targetPort: 80 # 컨테이너의 포트
      nodePort: 30080 # 외부로 노출되는 포트
